name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'
      - name: Debug token presence
        run: |
          if [ -n "$GH_TOKEN" ]; then
            echo "GH_TOKEN is SET"
          else
            echo "GH_TOKEN is NOT SET"
          fi
          
          if [ -n "$NPM_TOKEN" ]; then
            echo "NPM_TOKEN is SET"
          else
            echo "NPM_TOKEN is NOT SET"
          fi

      - name: Configure npm token
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - name: Test NPM whoami
        run: npm whoami

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage

      - name: Run semantic-release
        run: npx semantic-release
